---
title: "_00_eda_by_region"
author: "Julian Kleindiek"
date: "7/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(tidyverse)
library(kableExtra)
library(janitor)
library(maps)
library(geosphere)
library(data.table)

# set paths
path = "/Users/juliankleindiek/Desktop/UChicago/08_Quarter4/02_TimeSeries/Project"
filename = "_01_International_Report_Passengers.csv"
```


### Step 1. Read in data
```{r}
# set working directory
setwd(path)

# read in flight data 
df = fread(file.path(filename))

# save df as tibble
df <- as_tibble(df)

# print available columns
names(df)

# head
head(df)
```

### Step 2. Clean the data
```{r}
# to numeric
df$total = as.numeric(gsub(",", "", df$total))
df$scheduled = as.numeric(gsub(",", "", df$scheduled))
```


### Step 3. EDA by region
```{r}
# define regions
south_europe = c("PORTUGAL", "SPAIN", "MALTA", "CYPRUS", "FRANCE", "ITALY", "CROATIA", "GREECE")
southeast_asia = c("INDONESIA", "THAILAND", "MALAYSIA", "PHILIPPINES", "CAMBODIA") # "VIETNAM", "SINGAPUR", "LAOS"
south_america = c("BRAZIL", "ARGENTINA", "COLOMBIA", "PERU", "CHILE", "ECUADOR", "BOLIVIA")
oceania = c("AUSTRALIA", "NEW ZEALAND")
```

```{r}
# filter dat by given regions
df_south_europe = df %>% filter(fg_country %in% south_europe)
df_southeast_asia = df %>% filter(fg_country %in% southeast_asia)
df_south_america = df %>% filter(fg_country %in% south_america)
df_oceania = df %>% filter(fg_country %in% oceania)
```

```{r}
# aggregate by year
df_south_europe_y = aggregate(df_south_europe$total, by=list(cat1=df_south_europe$year), FUN=sum)
df_southeast_asia_y = aggregate(df_southeast_asia$total, by=list(cat1=df_southeast_asia$year), FUN=sum)
df_south_america_y= aggregate(df_south_america$total, by=list(cat1=df_south_america$year), FUN=sum)
df_oceania_y = aggregate(df_oceania$total, by=list(cat1=df_oceania$year), FUN=sum)

# create time series object
south_europe_ts_y = ts(df_south_europe_y$x, start=1990, end=2019, frequency = 1)
southeast_asia_ts_y = ts(df_southeast_asia_y$x, start=1990, end=2019, frequency = 1)
south_america_ts_y = ts(df_south_america_y$x, start=1990, end=2019, frequency = 1)
oceania_ts_y = ts(df_oceania_y$x, start=1990, end=2019, frequency = 1)

# plot
ts.plot(south_europe_ts_y, southeast_asia_ts_y, south_america_ts_y, oceania_ts_y,
        ylab="Number of passengers", xlab="Time", col=c("blue", "red", "green", "yellow"),
        main="International travel from the US by year")
legend("topleft", lty=c(1,1,1,1), col=c("blue", "red", "green", "yellow"),
       legend=c("South Europe", "Southeast Asia", "South America", "Oceania"))
```
\
- Note that 2019 data is not complete\


```{r}
# aggregate by month
df_south_europe_m = aggregate(df_south_europe$total, by=list(cat1=df_south_europe$year, 
                                                             cat2=df_south_europe$month), FUN=sum)
df_southeast_asia_m = aggregate(df_southeast_asia$total, by=list(cat1=df_southeast_asia$year, 
                                                             cat2=df_southeast_asia$month), FUN=sum)
df_south_america_m = aggregate(df_south_america$total, by=list(cat1=df_south_america$year, 
                                                             cat2=df_south_america$month), FUN=sum)
df_oceania_m = aggregate(df_oceania$total, by=list(cat1=df_oceania$year, 
                                                             cat2=df_oceania$month), FUN=sum)

# create time series object
south_europe_ts_m = ts(df_south_europe_m[order(df_south_europe_m$cat1),]$x, frequency = 12, start=c(1990,1))
southeast_asia_ts_m = ts(df_southeast_asia_m[order(df_southeast_asia_m$cat1),]$x, frequency = 12, start=c(1990,1))
south_america_ts_m = ts(df_south_america_m[order(df_south_america_m$cat1),]$x, frequency = 12, start=c(1990,1))
oceania_ts_m = ts(df_oceania_m[order(df_oceania_m$cat1),]$x, frequency = 12, start=c(1990,1))

# plot
ts.plot(south_europe_ts_m, southeast_asia_ts_m, south_america_ts_m, oceania_ts_m,
        ylab="Number of passengers", xlab="Time", col=c("blue", "red", "green", "yellow"),
        main="International travel from the US by month")
legend("topleft", lty=c(1,1,1,1), col=c("blue", "red", "green", "yellow"),
       legend=c("South Europe", "Southeast Asia", "South America", "Oceania"))
```
